# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FMSFToHMS
                                 A QGIS plugin
 This plugin is used to aid the processing and upload of FMSF data into HMS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-01
        copyright            : (C) 2020 by Legion GIS, LLC
        email                : adam@legiongis.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FMSFToHMS class from file FMSFToHMS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fmsf_hms import FMSFToHMS
    return FMSFToHMS(iface)
